<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту запись?',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создание экземпляра {modelClass}',
    'Created' => 'Создано',
    'Delete' => 'Удалить',
    'ID' => '',
    'Modified' => 'Отредактировано',
    'Search' => 'Поиск',
    'Update' => 'Редактировать',
    'Update {modelClass}: ' => 'Редактирование экземпляра {modelClass}: ',
    'NOT_SHOW_ON_MAIN' => 'Не показывать на главной',
    'SHOW_ON_MAIN' => 'Показывать на главной',
    'FAQ_ID' => 'ID',
    'FAQ_HEADER' => 'Заголовок',
    'FAQ_CONTENT' => 'Содержание',
    'FAQ_LANGUAGE' => 'Язык',
    'FAQ_IS_SHOW_ON_MAIN' => 'Отображать на главной (да/нет)',
    'FREQUENTLY_ASKED_QUESTIONS' => 'Часто задаваемые вопросы',
    'NO_DATA' => 'Данные для отображения не найдены'
 ];
