<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Are you sure you want to delete this item?',
    'Create' => 'Create',
    'Create {modelClass}' => 'Create {modelClass}',
    'Created' => 'Created',
    'Delete' => 'Delete',
    'ID' => '',
    'Modified' => 'Modified',
    'Search' => 'Search',
    'Update' => 'Update',
    'Update {modelClass}: ' => 'Update {modelClass}: ',
    'NOT_SHOW_ON_MAIN' => 'Not show on main',
    'SHOW_ON_MAIN' => 'Show on main',
    'FAQ_ID' => 'ID',
    'FAQ_HEADER' => 'Header',
    'FAQ_CONTENT' => 'Content',
    'FAQ_LANGUAGE' => 'Language',
    'FAQ_IS_SHOW_ON_MAIN' => 'Show on main (yes/no)',
    'FREQUENTLY_ASKED_QUESTIONS' => 'FAQ',
    'NO_DATA' => 'No data'
 ];
